spring.profiles.active=local

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DEBUG
spring.security.debug=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG